# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

networks:
  app-tier:
    driver: bridge
services:
  kafka:
    container_name: kafka-1
    image: docker.io/bitnami/kafka:3.7
    networks:
      - app-tier
    ports:
      - "9092:29092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics.sh",
          "--bootstrap-server=localhost:29092",
          "--list"
        ]
      start_period: 15s
      interval: 10s
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  init-kafka:
    image: docker.io/bitnami/kafka:3.7
    working_dir: /opt/bitnami/kafka/bin
    entrypoint: /bin/bash
    networks:
      - app-tier
    depends_on:
      kafka:
        condition: service_healthy
    command: |
      kafka-topics.sh --create --if-not-exists --topic OneToOne --replication-factor=1 --partitions=1 --bootstrap-server kafka-1:29092
volumes:
  kafka_data:
    driver: local
